### ISSUE TITLE
Failed to load Window

### ISSUE THREAD

**Issue by leon-lourenco** [Andrauss/WindowControllerFx#1]
Olá.

Estou tentando fechar uma tela e abrir outra. Mas recebo a seguinte exception:

```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: Failed to load window
	at br.com.fandrauss.fx.gui.WindowControllerFx.createStage(WindowControllerFx.java:388)
	at br.com.fandrauss.fx.gui.WindowControllerFx.showUndecorated(WindowControllerFx.java:335)
```

Esse é meu main, onde chamo a tela de login:

```
public class main extends Application {
    @Override
    public void start(Stage primaryStage) throws IOException {
        new LoginController().showUndecorated(false);
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

Após a validação do login, é chamado o método nextStage:

```
    @Override
    public void nextStage(Stage stage) {
        stage.close();
        Platform.runLater(() -> {
            new SelectorController().showUndecorated(false);
        });
    }
```

E é na instanciação do novo controller que a exception é recebida. 

```
public class SelectorController extends WindowControllerFx {

    @FXML
    private ImageView fecharImage;

    @FXML
    private ImageView minimizarImage;

    @FXML
    private JFXComboBox<Mosaicos> comboBox;

    private List<Mosaicos> mosaicos = new ArrayList<>();

    @FXML
    private JFXButton confirmButton;

    private void listarMosaicos() {
        MosaicSelectorImpl model = new MosaicSelectorImpl();
        List<Mosaicos> mosaicos = model.listar();
        ObservableList<Mosaicos> obsMosaicos = FXCollections.observableArrayList(mosaicos);
        comboBox.setItems(obsMosaicos);

    }

    private void minimizarJanela() {
        Stage stage = (Stage) confirmButton.getScene().getWindow();
        stage.setIconified(true);
    }

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        minimizarImage.setOnMouseClicked(event -> minimizarJanela());
        fecharImage.setOnMouseClicked(event -> System.exit(0));
        listarMosaicos();
    }

    @Override
    public String getFXML(){
        return "fxml/mosaicSelectorScene.fxml";
    }
```
O que pode ser?

**Comment by Andrauss** [comment]
Olá, vou realizar uns testes no projeto e te dou um feedback.

**Comment by leon-lourenco** [comment]
Baseado em testes antigos, o problema ocorre especificamente ao chamar o método "listar" do model.

Testei novamente. Quando você cria os itens da combobox no controller, tudo executa perfeitamente, mas ao tentar acessar um método do MosaicSelectorImpl ele dá exception.

**Comment by Andrauss** [comment]
Fiz algumas alterações na biblioteca, muitas delas já estavam prontas mas não publicadas. Subi um novo .jar e os fontes, fiz os testes localmente e estão ok.
